-include $(call mco_makefile_file, \
exclusive/makefile.project.exclusive \
isolation_levels/makefile.project.isolation_levels \
iterate/makefile.project.iterate \
mursiw/makefile.project.mursiw \
mvcc/makefile.project.mvcc \
nested/makefile.project.nested \
ph2commit/makefile.project.ph2commit \
ph2disk/makefile.project.ph2disk \
policy/makefile.project.policy \
transaction/makefile.project.transaction \
)
