-include $(call mco_makefile_file, \
errorhandler/makefile.project.errorhandler \
fatalerrex/makefile.project.fatalerrex \
fatalerr/makefile.project.fatalerr \
nonfatalerr/makefile.project.nonfatalerr \
statuscode/makefile.project.statuscode \
)
