MCO_ROOT=$(abspath ../../..)
include $(MCO_ROOT)/include/settings.makefile
include $(if $(findstring yes,$(MCO_QUICK_BUILD))$(findstring on,$(MCO_QUICK_BUILD)),,$(MCO_ROOT)/)makefile.cascade
include $(MCO_ROOT)/include/rules.makefile
