-include $(call mco_makefile_file, \
udacoll/makefile.project.udacoll \
udaevent/makefile.project.udaevent \
uda_mco/makefile.project.uda_mco \
udameta/makefile.project.udameta \
udaopen/makefile.project.udaopen \
udaops/makefile.project.udaops \
udapsearch/makefile.project.udapsearch \
udaudf/makefile.project.udaudf \
)
