/* Generated by eXtremeDB Schema Compiler, build 1036
 * at Tue Jul 14 16:01:20 2009
 */

#include "colldb.h"
#include "mcowrap.h"

#ifndef _WIN32
	#ifdef _VXWORKS
		#include <string.h>
	#endif 
#ifdef _ECOS
    #include <string.h>
#else 
#if !defined(_NETOS) && !defined(_VXWORKS)
    #include <strings.h>
#endif 
#endif 
    #define STR_CMP strcasecmp
#else 
    #include <string.h>
    #define STR_CMP stricmp
#endif 

/*
* API for the user-defined collation "C1"
*/

/* collation compare function */
int2  C1_collation_compare ( mco_collate_h c1, uint2 len1, mco_collate_h c2, uint2 len2)
{
  char buf1[15], buf2[15];

  mco_collate_get_char(c1, buf1, sizeof(buf1));
  mco_collate_get_char(c2, buf2, sizeof(buf2));

  return STR_CMP(buf1, buf2);
}

