/* Generated by eXtremeDB Schema Compiler, build 451
 * at Thu Dec 14 16:03:16 2006
 */

#include "udfdb.h"
#include "mcowrap.h"

#ifndef _WIN32
#ifdef _VXWORKS
	#include <string.h>
#endif 
#ifdef _ECOS
    #include <string.h>
#else 
#if !defined(_NETOS) && !defined(_VXWORKS)
    #include <strings.h>
#endif
#endif 
    #define STR_CMP strcasecmp
#else 
    #include <string.h>
    #define STR_CMP stricmp
#endif 
/*


 * API for the user-defined index "tudf"

 */

/* object-to-object user-defined compare function */
int2 Record_tudf_compare_obj(Record* handle1, Record* handle2)
{
    /* TODO: add your implementation here */
    char buf1[15];
    char buf2[15];
    uint2 len;

    Record_name_get(handle1, buf1, 15, &len);
    Record_name_get(handle2, buf2, 15, &len);


    return STR_CMP(buf1, buf2);
}

/* object-to-key user-defined compare function */
int2 Record_tudf_compare_ext(Record* handle, void** key)
{
    char buf[15];
    uint2 len;

    Record_name_get(handle, buf, 15, &len);

    return STR_CMP(buf, Record_tudf_extkey_name(key));
}
