DROP TABLE IF EXISTS datapoints;
DROP TABLE IF EXISTS representation;
DROP FUNCTION saxrep_alg;

CREATE TABLE datapoints (time TIMESTAMP, d0 DOUBLE PRECISION, d1 DOUBLE PRECISION, d2 DOUBLE PRECISION, d3 DOUBLE PRECISION, d4 DOUBLE PRECISION, d5 DOUBLE PRECISION, d6 DOUBLE PRECISION, d7 DOUBLE PRECISION, d8 DOUBLE PRECISION, d9 DOUBLE PRECISION, d10 DOUBLE PRECISION, d11 DOUBLE PRECISION, d12 DOUBLE PRECISION, d13 DOUBLE PRECISION, d14 DOUBLE PRECISION, d15 DOUBLE PRECISION, d16 DOUBLE PRECISION, d17 DOUBLE PRECISION, d18 DOUBLE PRECISION, d19 DOUBLE PRECISION, d20 DOUBLE PRECISION, d21 DOUBLE PRECISION, d22 DOUBLE PRECISION, d23 DOUBLE PRECISION, d24 DOUBLE PRECISION, d25 DOUBLE PRECISION, d26 DOUBLE PRECISION, d27 DOUBLE PRECISION, d28 DOUBLE PRECISION, d29 DOUBLE PRECISION, d30 DOUBLE PRECISION, d31 DOUBLE PRECISION, d32 DOUBLE PRECISION, d33 DOUBLE PRECISION, d34 DOUBLE PRECISION, d35 DOUBLE PRECISION, d36 DOUBLE PRECISION, d37 DOUBLE PRECISION, d38 DOUBLE PRECISION, d39 DOUBLE PRECISION, d40 DOUBLE PRECISION, d41 DOUBLE PRECISION, d42 DOUBLE PRECISION, d43 DOUBLE PRECISION, d44 DOUBLE PRECISION, d45 DOUBLE PRECISION, d46 DOUBLE PRECISION, d47 DOUBLE PRECISION, d48 DOUBLE PRECISION, d49 DOUBLE PRECISION, d50 DOUBLE PRECISION, d51 DOUBLE PRECISION, d52 DOUBLE PRECISION, d53 DOUBLE PRECISION, d54 DOUBLE PRECISION, d55 DOUBLE PRECISION, d56 DOUBLE PRECISION, d57 DOUBLE PRECISION, d58 DOUBLE PRECISION, d59 DOUBLE PRECISION, d60 DOUBLE PRECISION, d61 DOUBLE PRECISION, d62 DOUBLE PRECISION, d63 DOUBLE PRECISION, d64 DOUBLE PRECISION, d65 DOUBLE PRECISION, d66 DOUBLE PRECISION, d67 DOUBLE PRECISION, d68 DOUBLE PRECISION, d69 DOUBLE PRECISION, d70 DOUBLE PRECISION, d71 DOUBLE PRECISION, d72 DOUBLE PRECISION, d73 DOUBLE PRECISION, d74 DOUBLE PRECISION, d75 DOUBLE PRECISION, d76 DOUBLE PRECISION, d77 DOUBLE PRECISION, d78 DOUBLE PRECISION, d79 DOUBLE PRECISION, d80 DOUBLE PRECISION, d81 DOUBLE PRECISION, d82 DOUBLE PRECISION, d83 DOUBLE PRECISION, d84 DOUBLE PRECISION, d85 DOUBLE PRECISION, d86 DOUBLE PRECISION, d87 DOUBLE PRECISION, d88 DOUBLE PRECISION, d89 DOUBLE PRECISION, d90 DOUBLE PRECISION, d91 DOUBLE PRECISION, d92 DOUBLE PRECISION, d93 DOUBLE PRECISION, d94 DOUBLE PRECISION, d95 DOUBLE PRECISION, d96 DOUBLE PRECISION, d97 DOUBLE PRECISION, d98 DOUBLE PRECISION, d99 DOUBLE PRECISION);
CREATE TABLE representation(sax TEXT);

CREATE OR REPLACE FUNCTION get_time() RETURNS FLOAT
LANGUAGE PYTHON
{
        from datetime import datetime
        return (datetime.now() - datetime(1970, 1, 1)).total_seconds()
};

CREATE OR REPLACE FUNCTION saxrep_alg(time TIMESTAMP, d0 DOUBLE PRECISION, d1 DOUBLE PRECISION, d2 DOUBLE PRECISION, d3 DOUBLE PRECISION, d4 DOUBLE PRECISION, d5 DOUBLE PRECISION, d6 DOUBLE PRECISION, d7 DOUBLE PRECISION, d8 DOUBLE PRECISION, d9 DOUBLE PRECISION, d10 DOUBLE PRECISION, d11 DOUBLE PRECISION, d12 DOUBLE PRECISION, d13 DOUBLE PRECISION, d14 DOUBLE PRECISION, d15 DOUBLE PRECISION, d16 DOUBLE PRECISION, d17 DOUBLE PRECISION, d18 DOUBLE PRECISION, d19 DOUBLE PRECISION, d20 DOUBLE PRECISION, d21 DOUBLE PRECISION, d22 DOUBLE PRECISION, d23 DOUBLE PRECISION, d24 DOUBLE PRECISION, d25 DOUBLE PRECISION, d26 DOUBLE PRECISION, d27 DOUBLE PRECISION, d28 DOUBLE PRECISION, d29 DOUBLE PRECISION, d30 DOUBLE PRECISION, d31 DOUBLE PRECISION, d32 DOUBLE PRECISION, d33 DOUBLE PRECISION, d34 DOUBLE PRECISION, d35 DOUBLE PRECISION, d36 DOUBLE PRECISION, d37 DOUBLE PRECISION, d38 DOUBLE PRECISION, d39 DOUBLE PRECISION, d40 DOUBLE PRECISION, d41 DOUBLE PRECISION, d42 DOUBLE PRECISION, d43 DOUBLE PRECISION, d44 DOUBLE PRECISION, d45 DOUBLE PRECISION, d46 DOUBLE PRECISION, d47 DOUBLE PRECISION, d48 DOUBLE PRECISION, d49 DOUBLE PRECISION, d50 DOUBLE PRECISION, d51 DOUBLE PRECISION, d52 DOUBLE PRECISION, d53 DOUBLE PRECISION, d54 DOUBLE PRECISION, d55 DOUBLE PRECISION, d56 DOUBLE PRECISION, d57 DOUBLE PRECISION, d58 DOUBLE PRECISION, d59 DOUBLE PRECISION, d60 DOUBLE PRECISION, d61 DOUBLE PRECISION, d62 DOUBLE PRECISION, d63 DOUBLE PRECISION, d64 DOUBLE PRECISION, d65 DOUBLE PRECISION, d66 DOUBLE PRECISION, d67 DOUBLE PRECISION, d68 DOUBLE PRECISION, d69 DOUBLE PRECISION, d70 DOUBLE PRECISION, d71 DOUBLE PRECISION, d72 DOUBLE PRECISION, d73 DOUBLE PRECISION, d74 DOUBLE PRECISION, d75 DOUBLE PRECISION, d76 DOUBLE PRECISION, d77 DOUBLE PRECISION, d78 DOUBLE PRECISION, d79 DOUBLE PRECISION, d80 DOUBLE PRECISION, d81 DOUBLE PRECISION, d82 DOUBLE PRECISION, d83 DOUBLE PRECISION, d84 DOUBLE PRECISION, d85 DOUBLE PRECISION, d86 DOUBLE PRECISION, d87 DOUBLE PRECISION, d88 DOUBLE PRECISION, d89 DOUBLE PRECISION, d90 DOUBLE PRECISION, d91 DOUBLE PRECISION, d92 DOUBLE PRECISION, d93 DOUBLE PRECISION, d94 DOUBLE PRECISION, d95 DOUBLE PRECISION, d96 DOUBLE PRECISION, d97 DOUBLE PRECISION, d98 DOUBLE PRECISION, d99 DOUBLE PRECISION) RETURNS TABLE(sax TEXT)
LANGUAGE PYTHON
{
        import sys
        import numpy as np
        sys.path.append('/home/gabi/Thesis-master/Algorithms/sax')
        import saxtransformation

        matrix = np.array([d0, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24, d25, d26, d27, d28, d29, d30, d31, d32, d33, d34, d35, d36, d37, d38, d39, d40, d41, d42, d43, d44, d45, d46, d47, d48, d49, d50, d51, d52, d53, d54, d55, d56, d57, d58, d59, d60, d61, d62, d63, d64, d65, d66, d67, d68, d69, d70, d71, d72, d73, d74, d75, d76, d77, d78, d79, d80, d81, d82, d83, d84, d85, d86, d87, d88, d89, d90, d91, d92, d93, d94, d95, d96, d97, d98, d99]).T
        saxrep = saxtransformation.saxrepresentation( matrix )

        return saxrep
};

DECLARE lines INTEGER;
DECLARE columns INTEGER;
SET lines=100;
SET columns=100;

-- Writing data *************************************************************************************
DECLARE initial_time FLOAT;
DECLARE final_time FLOAT;
DECLARE total_size INTEGER;

SET initial_time = get_time();
COPY INTO datapoints FROM '/home/gabi/Thesis-master/Datasets/synthetic.txt.csv' USING DELIMITERS ',','\n';
SET final_time = get_time();
SET total_size = ( SELECT SUM(columnsize) FROM storage() WHERE table='datapoints' );

SELECT
        total_size as Total_size_bytes,
        CAST( (total_size) as FLOAT) / 1024.0 / 1024.0 as Total_size_megabytes,
        final_time - initial_time as Total_time_seconds,
        CAST(lines as FLOAT) / (final_time - initial_time) AS Throughput_inserts_per_second,
        CAST(lines * columns as FLOAT) / (final_time - initial_time) AS Throughput_values_per_second;
-- Writing data *************************************************************************************


-- SAX*******************************************************************************************
DECLARE initial_time_sax_transformation FLOAT;
DECLARE final_time_sax_transformation FLOAT;

SET initial_time_sax_transformation = get_time();
INSERT INTO representation SELECT * FROM saxrep_alg( (SELECT * FROM datapoints) );
SET final_time_sax_transformation = get_time();

SELECT final_time_sax_transformation - initial_time_sax_transformation as Time_seconds__sax;
-- SAX *******************************************************************************************

--SELECT * FROM representation;
