-include $(call mco_makefile_file, \
convhv/makefile.project.convhv \
conv/makefile.project.conv \
dbextend/makefile.project.dbextend \
disk_file/makefile.project.disk_file \
disk_multifile/makefile.project.disk_multifile \
disk_raid/makefile.project.disk_raid \
hybrid/makefile.project.hybrid \
nvram/makefile.project.nvram \
security/disk_cipher/makefile.project.disk_cipher \
security/disk_crc/makefile.project.disk_crc \
shared/makefile.project.shared \
)
